# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('concatenate', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=100)),
                ('num_staff', models.CharField(max_length=40)),
                ('invoice_date', models.DateField()),
                ('Value', models.IntegerField()),
                ('grant', models.CharField(blank=True, max_length=40, null=True)),
                ('accepted', models.CharField(blank=True, max_length=40, null=True)),
                ('invoiced', models.CharField(blank=True, max_length=40, null=True)),
                ('comment', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('node', models.CharField(max_length=20)),
                ('pro_date', models.DateField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=45, null=True)),
                ('instrument', models.CharField(blank=True, max_length=45, null=True)),
                ('person', models.CharField(blank=True, max_length=45, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('num_sample', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=20)),
                ('int_ext', models.CharField(blank=True, max_length=3, null=True)),
                ('state', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.CharField(blank=True, max_length=11, null=True)),
                ('user_define1', models.CharField(max_length=20)),
                ('user_define2', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cus_count', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
