# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0002_auto_20170420_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=2)),
                ('node_name', models.CharField(max_length=40)),
                ('node_area', models.CharField(max_length=20)),
                ('node_abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project',
            new_name='project_name',
        ),
    ]
