# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0004_remove_node_node_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_id',
        ),
    ]
