# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0005_remove_node_node_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='version',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='index_id',
            new_name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Value',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='concatenate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoiced',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='num_staff',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='year',
        ),
        migrations.AddField(
            model_name='invoice',
            name='bad_debt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='category_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='instrument',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='int_ext_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ma_staff',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='no_sample_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='person_invoice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project_invoice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reconcilliation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='running_total',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_define1_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_define2_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quote',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
