# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0006_auto_20170427_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='reconcilliation',
            new_name='reconciliation',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='person_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
