# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0008_auto_20170428_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
