# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0009_auto_20170428_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_num', models.CharField(blank=True, max_length=50, null=True)),
                ('quote_year', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('concatenate', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('quote_staff', models.CharField(blank=True, max_length=50, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('quote_value', models.CharField(blank=True, max_length=50, null=True)),
                ('grant', models.CharField(blank=True, max_length=50, null=True)),
                ('accept', models.CharField(blank=True, max_length=50, null=True)),
                ('invoiced_not', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
