# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0010_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='grant',
            new_name='grant_not',
        ),
    ]
