# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0011_auto_20170428_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
