# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0013_auto_20170428_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='num_sample',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
