# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_db', '0014_auto_20170428_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='num_sample',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
